
function initTheme(){const b=document.querySelector('.theme-toggle');const saved=localStorage.getItem('theme');if(saved)document.documentElement.dataset.theme=saved;b?.addEventListener('click',()=>{const n=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=n;localStorage.setItem('theme',n)})}
function initLibs(){if(window.renderMathInElement)renderMathInElement(document.body,{delimiters:[{left:'$$',right:'$$',display:true},{left:'$',right:'$',display:false}]});if(window.hljs)hljs.highlightAll()}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function renderQuiz(){const el=document.getElementById('quiz');const dataEl=document.getElementById('quiz-data');if(!el||!dataEl)return;const qs=JSON.parse(dataEl.textContent);window.quizData=qs;el.innerHTML=qs.map((q,i)=>renderQuestion(q,i)).join('');setupDnD();el.addEventListener('input',updateProgress);el.addEventListener('change',updateProgress);document.getElementById('checkQuiz').addEventListener('click',checkQuiz);updateProgress()}
function renderQuestion(q,i){let body='';if(q.type==='single')body=q.options.map((o,j)=>`<label class="option"><input type="radio" name="q${i}" value="${j}"> ${o}</label>`).join('');if(q.type==='multi')body=q.options.map((o,j)=>`<label class="option"><input type="checkbox" name="q${i}" value="${j}"> ${o}</label>`).join('');if(q.type==='text')body=`<input class="text-answer" name="q${i}" placeholder="Введите ответ">`;if(q.type==='match'){const vals=shuffle(Object.values(q.pairs));body=Object.keys(q.pairs).map(k=>`<div class="match-row"><strong>${k}</strong><select name="q${i}"><option value="">Выберите</option>${vals.map(v=>`<option>${v}</option>`).join('')}</select></div>`).join('')}if(q.type==='order')body=`<ul class="sortable" data-q="${i}">${shuffle(q.items).map(x=>`<li draggable="true">${x}</li>`).join('')}</ul>`;return `<section class="question" id="question-${i}" data-type="${q.type}"><h3>${i+1}. ${q.prompt}</h3>${body}<div class="feedback" hidden></div></section>`}
function setupDnD(){document.querySelectorAll('.sortable li').forEach(li=>{li.addEventListener('dragstart',()=>li.classList.add('dragging'));li.addEventListener('dragend',()=>{li.classList.remove('dragging');updateProgress()})});document.querySelectorAll('.sortable').forEach(list=>list.addEventListener('dragover',e=>{e.preventDefault();const dragging=document.querySelector('.dragging');const after=[...list.querySelectorAll('li:not(.dragging)')].find(x=>e.clientY<=x.getBoundingClientRect().top+x.offsetHeight/2);if(dragging)list.insertBefore(dragging,after||null)}))}
function answered(q,i){if(q.type==='single')return !!document.querySelector(`input[name=q${i}]:checked`);if(q.type==='multi')return document.querySelectorAll(`input[name=q${i}]:checked`).length>0;if(q.type==='text')return document.querySelector(`[name=q${i}]`).value.trim().length>0;if(q.type==='match')return [...document.querySelectorAll(`select[name=q${i}]`)].every(s=>s.value);if(q.type==='order')return true;return false}
function updateProgress(){if(!window.quizData)return;const n=window.quizData.filter((q,i)=>answered(q,i)).length;document.getElementById('progressText').textContent=`${n} из ${window.quizData.length}`;document.getElementById('progressBar').style.width=(100*n/window.quizData.length)+'%'}
function checkQuiz(){const qs=window.quizData;let score=0, mistakes=[];qs.forEach((q,i)=>{const box=document.getElementById(`question-${i}`);box.classList.remove('correct','wrong');let ok=false, right='';if(q.type==='single'){const v=document.querySelector(`input[name=q${i}]:checked`)?.value;ok=Number(v)===q.answer;right=q.options[q.answer]}if(q.type==='multi'){const vals=[...document.querySelectorAll(`input[name=q${i}]:checked`)].map(x=>Number(x.value)).sort().join(',');ok=vals===q.answer.slice().sort().join(',');right=q.answer.map(j=>q.options[j]).join('; ')}if(q.type==='text'){const v=document.querySelector(`[name=q${i}]`).value.toLowerCase();ok=q.answer.some(k=>v.includes(k.toLowerCase()));right=q.answer.join(' / ')}if(q.type==='match'){const keys=Object.keys(q.pairs);const vals=[...document.querySelectorAll(`select[name=q${i}]`)];ok=keys.every((k,j)=>vals[j].value===q.pairs[k]);right=keys.map(k=>`${k} — ${q.pairs[k]}`).join('; ')}if(q.type==='order'){const vals=[...document.querySelectorAll(`#question-${i} .sortable li`)].map(x=>x.textContent.trim());ok=vals.join('|')===q.items.join('|');right=q.items.join(' → ')}if(ok){score++;box.classList.add('correct')}else{box.classList.add('wrong');mistakes.push(`<li><strong>${i+1}.</strong> ${q.prompt}<br><em>Правильный ответ:</em> ${right}</li>`)}const fb=box.querySelector('.feedback');fb.hidden=false;fb.innerHTML=ok?'Верно.':`Неверно. Правильный ответ: ${right}`});const pct=Math.round(score*100/qs.length);document.getElementById('result').hidden=false;document.getElementById('result').innerHTML=`<h2>Результат: ${score} из ${qs.length} (${pct}%)</h2>${mistakes.length?'<h3>Ошибки</h3><ol>'+mistakes.join('')+'</ol>':'<p>Все ответы верны.</p>'}`;document.getElementById('result').scrollIntoView({behavior:'smooth'})}
document.addEventListener('DOMContentLoaded',()=>{initTheme();initLibs();renderQuiz()});
